DROP TABLE IF EXISTS products, deliveries, sales;

CREATE TABLE IF NOT EXISTS products
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(4096),
    price FLOAT CHECK (price >= 0),
    on_stock BOOLEAN,
    amount INT
);

CREATE TABLE IF NOT EXISTS deliveries
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL REFERENCES products(name),
    amount INT CHECK (amount >= 0)
);

CREATE TABLE IF NOT EXISTS sales
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL REFERENCES products(name),
    amount INT CHECK (amount >= 1),
    sum INT
);